[package]
name = "compiler2"
version = "0.1.0"
edition = "2021"

[dependencies]

clap = "2"
lalrpop-util = "0.19.6"
log = "0.4"
logos = "0.12"
petgraph = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
simple_logger = "1"

[build-dependencies]
lalrpop = "0.19.6"
